#!/bin/bash

IMAGE_NAME="$1"
IMAGE_TAG="$2"
REGISTRY_URI="$3"
REGISTRY_USERNAME="$4"
REGISTRY_PASSWORD="$5"

docker pull --platform linux/amd64 $IMAGE_NAME:$IMAGE_TAG
docker tag mysql:9.2.0 $REGISTRY_URI/$IMAGE_NAME:$IMAGE_TAG
docker login $REGISTRY_URI -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD 
docker push $REGISTRY_URI/$IMAGE_NAME:$IMAGE_TAG